import './globals.css'

import { Kalam } from 'next/font/google'


export const metadata = {
  title: 'Todo React App',
  description: 'Generated by create next app',
  icons: {
    icon: '/icon.png',
  }
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="text-sofia">{children}</body>
    </html>
  )
}
