import './globals.css'

import { Kalam } from 'next/font/google'

import { Montserrat } from 'next/font/google'

export const metadata = {
  title: 'Todo React App',
  description: 'Generated by create next app',
  icons: {
    icon: '/icon.png',
  }
}

const montserrat = Montserrat({ subsets: ['latin'], weight: ['400'] })

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={montserrat.className}>{children}</body>
    </html>
  )
}
